# Generated by Django 5.0.7 on 2024-07-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
